//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLite.Reflection.Dynamic.Internal {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLite.Reflection.Dynamic.Internal.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot adapt proxy to interface type. 的本地化字符串。
        /// </summary>
        internal static string CannotAdaptProxy {
            get {
                return ResourceManager.GetString("CannotAdaptProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructor on type &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string ConstructorOnTypeNotFound {
            get {
                return ResourceManager.GetString("ConstructorOnTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamic assembly key pair is missing. 的本地化字符串。
        /// </summary>
        internal static string DynamicAssemblyKeyPairIsMissing {
            get {
                return ResourceManager.GetString("DynamicAssemblyKeyPairIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interface type &apos;{0}&apos; must not be a generic type definition. 的本地化字符串。
        /// </summary>
        internal static string InterfaceTypeMustNotBeAGenericTypeDefinition {
            get {
                return ResourceManager.GetString("InterfaceTypeMustNotBeAGenericTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interface type must not be null. 的本地化字符串。
        /// </summary>
        internal static string InterfaceTypeMustNotBeNull {
            get {
                return ResourceManager.GetString("InterfaceTypeMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interface type {0} was already added. 的本地化字符串。
        /// </summary>
        internal static string InterfaceTypeWasAlreadyAdded {
            get {
                return ResourceManager.GetString("InterfaceTypeWasAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid proxy type. 的本地化字符串。
        /// </summary>
        internal static string InvalidProxyType {
            get {
                return ResourceManager.GetString("InvalidProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member has no declaring type. 的本地化字符串。
        /// </summary>
        internal static string MemberHasNoDeclaringType {
            get {
                return ResourceManager.GetString("MemberHasNoDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method is not declared or inherited by target object. 的本地化字符串。
        /// </summary>
        internal static string MethodNotDeclaredOrInherited {
            get {
                return ResourceManager.GetString("MethodNotDeclaredOrInherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method is not implemented by target object. 的本地化字符串。
        /// </summary>
        internal static string MethodNotImplemented {
            get {
                return ResourceManager.GetString("MethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}&apos; is not overridable. 的本地化字符串。
        /// </summary>
        internal static string MethodNotOverridable {
            get {
                return ResourceManager.GetString("MethodNotOverridable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}&apos; on type &apos;{1}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string MethodOnTypeNotFound {
            get {
                return ResourceManager.GetString("MethodOnTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method requires a target object. 的本地化字符串。
        /// </summary>
        internal static string MethodRequiresATargetObject {
            get {
                return ResourceManager.GetString("MethodRequiresATargetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more interceptors in the interceptor chain. 的本地化字符串。
        /// </summary>
        internal static string NoMoreInterceptorsInTheInterceptorChain {
            get {
                return ResourceManager.GetString("NoMoreInterceptorsInTheInterceptorChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of parameter types and names must be equal. 的本地化字符串。
        /// </summary>
        internal static string NumberOfParameterTypesAndNamesMustBeEqual {
            get {
                return ResourceManager.GetString("NumberOfParameterTypesAndNamesMustBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent type must not be a generic type definition. 的本地化字符串。
        /// </summary>
        internal static string ParentTypeMustNotBeAGenericTypeDefinition {
            get {
                return ResourceManager.GetString("ParentTypeMustNotBeAGenericTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent type must not be sealed. 的本地化字符串。
        /// </summary>
        internal static string ParentTypeMustNotBeSealed {
            get {
                return ResourceManager.GetString("ParentTypeMustNotBeSealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; is not an interface type. 的本地化字符串。
        /// </summary>
        internal static string TypeNotAnInterfaceType {
            get {
                return ResourceManager.GetString("TypeNotAnInterfaceType", resourceCulture);
            }
        }
    }
}
